# Generated by Django 2.2.3 on 2019-07-17 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexiiapp', '0002_auto_20190717_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usertype',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterModelTable(
            name='usertype',
            table='user_type',
        ),
    ]
