# Generated by Django 2.2.3 on 2019-07-18 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexiiapp', '0003_auto_20190717_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='techincal_skills',
            new_name='technical_skills',
        ),
    ]
