# Generated by Django 2.2.3 on 2019-07-18 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexiiapp', '0004_auto_20190718_0525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='actor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='requirement_actor', to='nexiiapp.User'),
        ),
        migrations.AlterField(
            model_name='usertoken',
            name='browser_agent',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
