# Generated by Django 2.2.3 on 2019-07-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexiiapp', '0006_auto_20190723_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionhistory',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
