# Generated by Django 2.2.3 on 2019-07-23 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexiiapp', '0007_auto_20190723_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactionhistory',
            name='upload_id',
        ),
    ]
