# Generated by Django 2.2.3 on 2019-07-23 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexiiapp', '0008_remove_transactionhistory_upload_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionhistory',
            name='upload_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='transaction_upload_id', to='nexiiapp.Upload'),
            preserve_default=False,
        ),
    ]
